-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying(30) NOT NULL,
    website character varying(30) NOT NULL,
    phone_number character varying(10) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_seekers
(
    user_id integer NOT NULL,
    first_name character varying(30) NOT NULL,
    last_name character varying(30) NOT NULL,
    identity_number character varying(11) NOT NULL,
    year_of_birth character varying(4) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.jobs
(
    job_id integer NOT NULL,
    job_name character varying(30) NOT NULL,
    PRIMARY KEY (job_id)
);

CREATE TABLE public.system_personnels
(
    user_id integer NOT NULL,
    first_name character varying(30) NOT NULL,
    last_name character varying(30) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.users
(
    user_id integer NOT NULL,
    email character varying(30) NOT NULL,
    password character varying(30) NOT NULL,
    PRIMARY KEY (user_id)
);

ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.system_personnels
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;

END;